/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/views/404/index.vue')['default']
    Attributes: typeof import('./src/views/product/attributes/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Home: typeof import('./src/views/home/index.vue')['default']
    Login: typeof import('./src/views/login/index.vue')['default']
    Logo: typeof import('./src/views/home/logo/index.vue')['default']
    Main: typeof import('./src/views/home/main/index.vue')['default']
    Menu: typeof import('./src/views/home/menu/index.vue')['default']
    MenuManage: typeof import('./src/views/access-control/menu-manage/index.vue')['default']
    Role: typeof import('./src/views/access-control/role/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Screen: typeof import('./src/views/screen/index.vue')['default']
    Sku: typeof import('./src/views/product/sku/index.vue')['default']
    Spu: typeof import('./src/views/product/spu/index.vue')['default']
    TopNav: typeof import('./src/views/home/top-nav/index.vue')['default']
    TopNavLeft: typeof import('./src/views/home/top-nav/top-nav-left/index.vue')['default']
    TopNavRight: typeof import('./src/views/home/top-nav/top-nav-right/index.vue')['default']
    Trademark: typeof import('./src/views/product/trademark/index.vue')['default']
    User: typeof import('./src/views/access-control/user/index.vue')['default']
  }
}
